# Generated by Django 4.2.7 on 2026-08-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Загрузите видео в формате MP4, WebM или OGG', upload_to='product_videos/', verbose_name='Видео')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название видео')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное видео')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product')),
            ],
            options={
                'verbose_name': 'Видео товара',
                'verbose_name_plural': 'Видео товаров',
                'ordering': ('order', 'created'),
            },
        ),
    ]
