# Generated by Django 4.2.7 on 2026-08-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(help_text='Загрузите видео в формате MP4, WebM, OGG или MOV', upload_to='product_videos/', verbose_name='Видео'),
        ),
    ]
