# Generated by Django 4.2.7 on 2026-08-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideo',
            name='converted',
            field=models.BooleanField(default=False, verbose_name='Сконвертировано'),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product_videos/thumbnails/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(help_text='Загрузите видео (поддерживаются MP4, MOV, AVI, WebM, OGG)', upload_to='product_videos/', verbose_name='Видео'),
        ),
    ]
