# Generated by Django 4.2.7 on 2026-08-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productvideo_converted_productvideo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Уход за вещами'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Состав материала'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна-изготовитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='fastener_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вид застежки'),
        ),
        migrations.AddField(
            model_name='product',
            name='height_on_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Рост на модели'),
        ),
        migrations.AddField(
            model_name='product',
            name='lining_material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал подкладки'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_params',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Параметры модели (ОГ-ОТ-ОБ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='russian_size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Российский размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='set_composition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Состав комплекта'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_on_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Размер на модели'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='sleeve',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Рукав'),
        ),
    ]
