# Generated by Django 4.2.7 on 2026-09-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality_document',
            field=models.URLField(blank=True, help_text='Вставьте ссылку на сертификат или документ качества (например, из S3)', max_length=500, null=True, verbose_name='Ссылка на документ качества'),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_document_name',
            field=models.CharField(blank=True, help_text='Например: Сертификат соответствия', max_length=200, null=True, verbose_name='Название документа'),
        ),
    ]
