# Generated by Django 4.2.7 on 2026-09-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_quality_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Фото'), ('video', 'Видео')], default='image', max_length=10, verbose_name='Тип')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/images/', verbose_name='Фото')),
                ('video', models.FileField(blank=True, null=True, upload_to='reviews/videos/', verbose_name='Видео')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='reviews/thumbnails/', verbose_name='Превью видео')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='products.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Медиа отзыва',
                'verbose_name_plural': 'Медиа отзывов',
                'ordering': ('order', 'created'),
            },
        ),
    ]
