# Generated by Django 4.2.7 on 2026-09-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=500, help_text='Вес товара в граммах. Используется для расчёта доставки СДЭК.', verbose_name='Вес, грамм'),
        ),
    ]
