# Generated by Django 4.2.7 on 2026-10-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Сколько раз открывали страницу товара', verbose_name='Просмотров'),
        ),
    ]
