# Generated by Django 4.2.7 on 2026-10-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_count_auth',
            field=models.PositiveIntegerField(default=0, help_text='Сколько раз открывали страницу товара авторизованные пользователи', verbose_name='Просмотров авторизованными'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Сколько раз открывали страницу товара (всего)', verbose_name='Просмотров'),
        ),
    ]
