# Generated by Django 4.2.7 on 2026-10-02 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0018_productview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='Путь')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Ключ сессии')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Просмотрено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр сайта',
                'verbose_name_plural': 'Просмотры сайта',
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='ProductView',
        ),
        migrations.AddIndex(
            model_name='siteview',
            index=models.Index(fields=['created'], name='products_si_created_06efba_idx'),
        ),
        migrations.AddIndex(
            model_name='siteview',
            index=models.Index(fields=['city'], name='products_si_city_b3154b_idx'),
        ),
    ]
