# Generated by Django 4.2.7 on 2026-10-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_siteview_delete_productview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteview',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, verbose_name='User-Agent'),
        ),
    ]
