# Generated by Django 4.2.7 on 2026-10-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_siteview_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
    ]
