# Generated by Django 4.2.7 on 2026-10-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='Отклонён'),
        ),
    ]
