# Generated by Django 4.2.7 on 2026-08-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_address_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_point',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_point_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес пункта выдачи'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_point_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код пункта выдачи'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_point_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название пункта выдачи'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('sdek', 'СДЭК'), ('yandex', 'Яндекс-доставка'), ('5post', '5 Пост'), ('boxberry', 'Boxberry'), ('courier', 'Курьерская доставка'), ('pickup', 'Самовывоз')], max_length=20, null=True, verbose_name='Способ доставки'),
        ),
    ]
