# Generated by Django 4.2.7 on 2026-09-25 08:27

import apps.orders.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_review_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('size', 'Не подошёл размер'), ('quality', 'Брак / дефект'), ('wrong', 'Пришёл не тот товар'), ('damaged', 'Повреждён при доставке'), ('not_fit', 'Не подошёл по другим причинам'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Причина возврата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('status', models.CharField(choices=[('new', '🆕 Новая'), ('review', '🔍 На рассмотрении'), ('approved', '✅ Одобрена'), ('rejected', '❌ Отклонена'), ('completed', '🏁 Завершена'), ('cancelled', '🚫 Отменена клиентом')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработан')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order', verbose_name='Заказ')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ReturnPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.orders.models.return_photo_upload_path, verbose_name='Фото')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.return', verbose_name='Возврат')),
            ],
            options={
                'verbose_name': 'Фото возврата',
                'verbose_name_plural': 'Фото возврата',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Размер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='orders.orderitem', verbose_name='Позиция заказа')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Товар')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.return', verbose_name='Возврат')),
            ],
            options={
                'verbose_name': 'Позиция возврата',
                'verbose_name_plural': 'Позиции возврата',
            },
        ),
    ]
