# Generated by Django 4.2.7 on 2026-09-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_return_returnphoto_returnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Заполняется автоматически при смене статуса на «Доставлен».', null=True, verbose_name='Дата доставки'),
        ),
    ]
