# Generated by Django 4.2.7 on 2026-09-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cdek_number',
            field=models.CharField(blank=True, help_text='Номер накладной, присвоенный СДЭК', max_length=50, null=True, verbose_name='Номер накладной СДЭК'),
        ),
        migrations.AddField(
            model_name='order',
            name='cdek_order_uuid',
            field=models.CharField(blank=True, help_text='UUID, возвращённый СДЭК при создании заказа', max_length=100, null=True, verbose_name='UUID заказа в СДЭК'),
        ),
        migrations.AddField(
            model_name='order',
            name='cdek_status_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код статуса СДЭК'),
        ),
        migrations.AddField(
            model_name='order',
            name='cdek_status_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название статуса СДЭК'),
        ),
    ]
