# Generated by Django 4.2.7 on 2026-09-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_cdek_number_order_cdek_order_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма возврата'),
        ),
        migrations.AddField(
            model_name='return',
            name='refund_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID возврата в ЮKassa'),
        ),
        migrations.AddField(
            model_name='return',
            name='refund_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус возврата'),
        ),
        migrations.AddField(
            model_name='return',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
    ]
