# Generated by Django 4.2.7 on 2026-09-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_return_refund_amount_return_refund_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='cdek_return_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер накладной возврата СДЭК'),
        ),
        migrations.AddField(
            model_name='return',
            name='cdek_return_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UUID возврата в СДЭК'),
        ),
    ]
