# Generated by Django 4.2.7 on 2026-10-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_return_cdek_return_number_return_cdek_return_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='cdek_return_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус возврата СДЭК'),
        ),
        migrations.AlterField(
            model_name='return',
            name='cdek_return_uuid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UUID возврата СДЭК'),
        ),
    ]
