# Generated by Django 4.2.7 on 2026-10-02 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_views_count_auth_alter_product_views_count'),
        ('orders', '0015_return_cdek_return_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='products.product'),
        ),
    ]
