# Generated by Django 4.2.7 on 2026-09-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('version', models.CharField(blank=True, help_text='Например: 1.0, 2.1. Необязательно.', max_length=50, null=True, verbose_name='Версия')),
                ('text', models.TextField(verbose_name='Текст оферты')),
                ('is_active', models.BooleanField(default=True, help_text='Активная оферта показывается пользователям.', verbose_name='Активна')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Оферта',
                'verbose_name_plural': 'Оферты',
                'ordering': ('-is_active', '-created'),
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='offer_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия оферты'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='offer_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_by_users', to='accounts.offer', verbose_name='Принятая оферта'),
        ),
    ]
