# Generated by Django 4.2.7 on 2026-09-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_data_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='personal_data_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия на обработку ПД'),
        ),
    ]
