# Generated by Django 4.2.7 on 2026-09-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_personal_data_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_data_consent_revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отзыва согласия на обработку ПД'),
        ),
    ]
