# Generated by Django 4.2.7 on 2026-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_personal_data_consent_revoked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='webpush_enabled',
            field=models.BooleanField(default=True, verbose_name='Пуш-уведомления включены'),
        ),
    ]
