# Generated by Django 4.2.7 on 2026-09-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_webpush_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat/attachments/%Y/%m/', verbose_name='Файл')),
                ('attachment_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('file', 'Файл')], max_length=10)),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер в байтах')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.chatmessage')),
            ],
            options={
                'verbose_name': 'Вложение чата',
                'verbose_name_plural': 'Вложения чата',
            },
        ),
    ]
