# Generated by Django 4.2.7 on 2026-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_period_years', models.PositiveIntegerField(default=0, help_text='Сколько лет даётся на подачу заявки на возврат после доставки.', verbose_name='Лет')),
                ('return_period_months', models.PositiveIntegerField(default=0, verbose_name='Месяцев')),
                ('return_period_weeks', models.PositiveIntegerField(default=0, verbose_name='Недель')),
                ('return_period_days', models.PositiveIntegerField(default=14, help_text='По умолчанию — 14 дней (Закон о защите прав потребителей).', verbose_name='Дней')),
                ('return_period_hours', models.PositiveIntegerField(default=0, verbose_name='Часов')),
                ('return_period_minutes', models.PositiveIntegerField(default=0, verbose_name='Минут')),
            ],
            options={
                'verbose_name': 'Настройки магазина',
                'verbose_name_plural': 'Настройки магазина',
            },
        ),
    ]
