# Generated by Django 4.2.7 on 2026-09-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_settings.shopsettings',),
        ),
        migrations.CreateModel(
            name='ReturnSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Возвраты',
                'verbose_name_plural': 'Возвраты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_settings.shopsettings',),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='return_period_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Лет'),
        ),
    ]
