# Generated by Django 4.2.7 on 2026-10-06 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0002_ordersettings_returnsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitEconomics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Юнит-экономика', max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Что считаем, какие допущения', verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Юнит-экономика',
                'verbose_name_plural': 'Юнит-экономика',
            },
        ),
        migrations.CreateModel(
            name='UnitFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "Маржа с заказа", "Точка безубыточности"', max_length=200, verbose_name='Название формулы')),
                ('formula', models.TextField(help_text='Используйте названия переменных. Пример: revenue - cost - cpa - tax. Операторы: + - * / ( )', verbose_name='Формула')),
                ('description', models.TextField(blank=True, help_text='Что считает эта формула и как её читать', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='shop_settings.uniteconomics', verbose_name='Юнит-экономика')),
            ],
            options={
                'verbose_name': 'Формула юнит-экономики',
                'verbose_name_plural': 'Формулы юнит-экономики',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='UnitVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Латиницей, без пробелов. Например: revenue, cost, cpa, tax', max_length=100, verbose_name='Название переменной')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Значение переменной')),
                ('description', models.CharField(blank=True, help_text='Для чего эта переменная — чтобы потом не забыть', max_length=255, verbose_name='Описание')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='shop_settings.uniteconomics', verbose_name='Юнит-экономика')),
            ],
            options={
                'verbose_name': 'Переменная юнит-экономики',
                'verbose_name_plural': 'Переменные юнит-экономики',
                'ordering': ('name',),
                'unique_together': {('unit', 'name')},
            },
        ),
    ]
