# Generated by Django 4.2.7 on 2026-10-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0003_uniteconomics_unitformula_unitvariable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitformula',
            name='formula',
        ),
        migrations.AddField(
            model_name='unitformula',
            name='expression',
            field=models.JSONField(default=list, help_text='Собирается из блоков в конструкторе', verbose_name='Формула'),
        ),
        migrations.AlterField(
            model_name='unitformula',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='unitformula',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название формулы'),
        ),
        migrations.AlterField(
            model_name='unitvariable',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='unitvariable',
            name='name',
            field=models.CharField(help_text='Латиницей, без пробелов. Например: tax, cost, cpa', max_length=100, verbose_name='Название переменной'),
        ),
        migrations.AlterField(
            model_name='unitvariable',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Значение'),
        ),
    ]
