# Generated by Django 4.2.7 on 2026-10-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0004_remove_unitformula_formula_unitformula_expression_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitformula',
            options={'ordering': ('order', 'pk'), 'verbose_name': 'Формула юнит-экономики', 'verbose_name_plural': 'Формулы юнит-экономики'},
        ),
        migrations.AddField(
            model_name='unitformula',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Меньше — выше в списке на дашборде. При равенстве — по дате создания.', verbose_name='Порядок показа'),
        ),
    ]
