# Generated by Django 4.2.7 on 2026-10-07 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_siteview_user_agent'),
        ('shop_settings', '0005_alter_unitformula_options_unitformula_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Себестоимость')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='products.product', verbose_name='Товар')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_costs', to='shop_settings.uniteconomics', verbose_name='Юнит-экономика')),
            ],
            options={
                'verbose_name': 'Себестоимость товара',
                'verbose_name_plural': 'Себестоимости товаров',
                'ordering': ('product__name',),
            },
        ),
    ]
