# Generated by Django 4.2.7 on 2026-10-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0006_productcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitformula',
            name='is_total',
            field=models.BooleanField(default=False, help_text='Если отмечено, эта формула показывается в подвале дашборда, а не в основном списке.', verbose_name='Итоговое значение'),
        ),
    ]
