# Generated by Django 4.2.7 on 2026-10-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0007_unitformula_is_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Название города, как оно приходит из геолокации (совпадает с SiteView.city)', max_length=100, unique=True, verbose_name='Город')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Исключённый город',
                'verbose_name_plural': 'Исключённые города',
                'ordering': ('city',),
            },
        ),
    ]
